name: CD

on:
  release:
    types: [created]

  jobs:
    publish:
      strategy:
        matrix:
          platform: ["ubuntu-lastest", "window-lastest"]
          node-version: [10.x, 12.x, 14.x, 15.x]
      name: Publish package to npm on ${{ matrix.platform }}
      runs-on: ${{ matrix.platform }}
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: "https://registry.npmjs.org"
        - run: npm ci
        - run: npm run build   
        - run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}