name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build
    strategy:
      matrix:
        platform: ["ubuntu-lastest", "window-lastest"]
        node-version: [10.x, 12.x, 14.x, 15.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build