name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build
    strategy:
      matrix:
        platform: ["ubuntu-latest", "windows-latest"]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci
      - name: Lint and format
        run: npm run lint
        run: npm run format

      - name: Build
        run: npm run build